[paths]
DATA_DIR = "APP_DATA"  

[files]
# parquet/geojson
GEOJSON = "nbhds.geojson"
ECON    = "econ.parquet"
DEMOS   = "demos.parquet"
RENOS   = "renos.parquet"
BUILDS  = "builds.parquet"
PERMITS = "permits.parquet"

# csvs (use explicit .csv to avoid Windows hidden-extensions confusion)
KENDALL = "kendall.csv"
SPEARMAN = "spearman.csv"
VIS_CLUSTERS_BUILDS = "vis_clusters_builds.csv"
VIS_CLUSTERS_DEMOS  = "vis_clusters_demos.csv"
VIS_CLUSTERS_RENOS  = "vis_clusters_renos.csv"
DATA_LINKS = "data_links.md"


[remote]
USE_REMOTE = false